# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# It is used to initialize a new eris:db node.
# For more info about the various options, 
# see https://github.com/eris-ltd/mint-client (mintgen).

moniker = "pizzaVAL1"
seeds = "159.203.31.229:46656,159.203.60.251:46656,45.55.217.124:46656"
fast_sync = false
db_backend = "leveldb"
log_level = "debug"
node_laddr = "0.0.0.0:46656"
rpc_laddr = "0.0.0.0:46657"
vm_log = false
